In [1]:
import pandas as pd 
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

In [1]:
score_threshold_col=['Original','is_0.1score','is_0.2score','is_0.3score','is_0.4score','is_0.5score','is_0.6score','is_0.7score']

In [6]:
# File_Path는 분류된 파일의 경로를 입력
file_path_neg=r"C:\Git_for_study\DE\Work\Neg_data\sample_neg_df_260730(2).xlsx"
scoring_soaring=pd.read_excel(file_path_neg, header=0)
soar_scoring_matrix=scoring_soaring.iloc[:,4:] # 실제 파일 구조 확인해서 몇 열까지 살릴지 고민해야함

In [7]:
soar_scoring_matrix

,Original,is_0.1score,is_0.2score,is_0.3score,is_0.4score,is_0.5score,is_0.6score,is_0.7score
0,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,0,0
4,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...
775,1,1,1,1,1,1,1,1
776,1,1,1,1,1,1,1,1
777,1,1,1,1,1,0,0,0
778,1,1,1,1,1,0,0,0
779,1,1,1,1,1,0,0,0

In [8]:
# Confusion_matrix 반환하는 함수
y_true = soar_scoring_matrix['AI_Label'].astype(int)
confusion_matrix_dict = {}

def matrix_extractor(df):
    for y_pred_col in score_threshold_col:
        # 해당 임계점의 예측값 가져오기
        y_pred = df[y_pred_col].astype(int)
        
        # 혼동행렬 계산
        cm = confusion_matrix(y_true, y_pred)
        tn, fp, fn, tp = cm.ravel()
        
        # 딕셔너리에 저장! (이름을 confusion_matrix_dict로 정확히 맞춤)
        confusion_matrix_dict[y_pred_col] = [tn, fp, fn, tp]
    cm_df_soar = pd.DataFrame(confusion_matrix_dict, index=['TN(정답)', 'FP(오탐)', 'FN(미탐)', 'TP(정답)'])
    return cm_df_soar

KeyError: 'AI_Label'

In [18]:
soar_matrix=matrix_extractor(soar_scoring_matrix)

In [19]:
soar_matrix

        is_0.4score  is_0.5score  is_0.6score  is_0.7score
TN(정답)            5          209          311          335
FP(오탐)          368          164           62           38
FN(미탐)            5          214          305          320
TP(정답)          322          113           22            7

In [20]:
soar_matrix.to_excel('soar_cm.xlsx',header=True)

In [22]:
neg_scoring_matrix

     is_0.4score  is_0.5score  is_0.6score  is_0.7score
0              1            1            0            0
1              1            1            1            0
2              1            1            0            0
3              1            1            0            0
4              1            1            0            0
..           ...          ...          ...          ...
775            1            0            0            0
776            1            0            0            0
777            1            1            0            0
778            0            0            0            0
779            1            0            0            0

[780 rows x 4 columns]

In [32]:
# Confusion_matrix 반환하는 함수
y_true = neg_scoring_matrix['AI_Label'].astype(int)
confusion_matrix_dict = {}

def matrix_extractor(df):
    for y_pred_col in score_threshold_col:
        # 해당 임계점의 예측값 가져오기
        y_pred = df[y_pred_col].astype(int)
        
        # 혼동행렬 계산
        cm = confusion_matrix(y_true, y_pred)
        tn, fp, fn, tp = cm.ravel()
        
        # 딕셔너리에 저장! (이름을 confusion_matrix_dict로 정확히 맞춤)
        confusion_matrix_dict[y_pred_col] = [tn, fp, fn, tp]
    cm_df_neg = pd.DataFrame(confusion_matrix_dict, index=['TN(정답)', 'FP(오탐)', 'FN(미탐)', 'TP(정답)'])
    return cm_df_neg

In [36]:
neg_matrix=matrix_extractor(neg_scoring_matrix)

In [37]:
neg_matrix.to_excel('neg_cm.xlsx',header=True)