Naver API
Client ID : 9q7w7kzlkz
Client Secret : 9oJbtNtakJ9vI2ipVbJkbco6YlJvorvzBF3nvUtG

In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time
import numpy as np
import supabase

In [31]:
API_URL = "https://naverapihub.apigw.ntruss.com/search/v1/blog" 
CLIENT_ID='9q7w7kzlkz' # -> 도커 말아 올릴 땐 변경 필요
CLIENT_SECRET_KEY='9oJbtNtakJ9vI2ipVbJkbco6YlJvorvzBF3nvUtG' # -> 도커 말아 올릴 땐 변경 필요
headers={'X-NCP-APIGW-API-KEY-ID':CLIENT_ID,
         'X-NCP-APIGW-API-KEY':CLIENT_SECRET_KEY}
keywords=['신혼부부 필수템','신혼부부 필수품','신혼부부 강추템','신혼부부 추천템']
body_data=[]

HEADERS_FOR_CRAWLER = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36")}

In [18]:
def blog_extractor(start_num=1, target_number=100, batch_size=100):
    data_dict={}
    
    for keyword in keywords:
        total_data=[]
        
        for start in range(start_num, target_number+1, batch_size):
            params={'query':keyword,
            'display':batch_size,
            'start':start,
            'sort':'date',
            'format':'json'}

            try:
                response=requests.get(
                    API_URL,
                    headers=headers,
                    params=params,
                    timeout=15
                )
                response.raise_for_status()
                items=response.json().get('items',[])
                
                if not items:
                    break
                
                total_data.extend(items)                
            except Exception as e:
                print(e)
                break
        
        data_dict[keyword]=total_data
        
    rows=[]
    for keyword, items in data_dict.items():
        for item in items:
            row=item.copy()
            row['keyword']= keyword
            rows.append(row)
    df=pd.json_normalize(rows)
    if df.empty:
        return df
    
    df=df.drop_duplicates(
        subset=['link'],
        keep='first',
        ignore_index=True
    )
    
    df=df.drop(columns=['description','bloggername','bloggerlink'])
    return df

In [19]:
df=blog_extractor()
df.head()

,title,link,postdate,keyword
0,테팔 퍼펙트 레지스트 냄비 20cm 솔직 사용기,https://blog.naver.com/zkt3u4br26t/224440338760,20261013,신혼부부 필수템
1,요리 초보도 고수 만들어주는 주방<b>필수템</b>! / 휘슬러 샌프란시스코 ....,https://blog.naver.com/doldolmanyo/224440331187,20261013,신혼부부 필수템
2,LG 트롬 오브제컬렉션 세탁기건조기 세트와 식기세척기 직접 써본 ....,https://blog.naver.com/zvav2pfuy8j/224440330152,20261013,신혼부부 필수템
3,스포틀러 워킹패드 애슬레틱 런닝머신 직접 써본 솔직 사용기,https://blog.naver.com/cgef708bgaglpv7/2244403...,20261013,신혼부부 필수템
4,&quot;거실 넓히겠다고 베란다 다 텄다가 결국 피눈물 흘립니다&quot; 506...,https://blog.naver.com/enzzuya/224440317193,20261013,신혼부부 필수템

In [32]:

def body_text_extractor(url):
    print('블로그 본문을 수집합니다.')
    
    rng = np.random.default_rng()

    
    
    try:
        # 1. 외부 네이버 블로그 페이지 요청
        response = requests.get(
            url,
            headers=HEADERS_FOR_CRAWLER,
            timeout=10
        )
        
        response.raise_for_status()

        outer_soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # 2. 실제 본문을 담은 iframe 주소 찾기
        iframe = outer_soup.select_one("iframe#mainFrame")

        if iframe is not None and iframe.get("src"):
            inner_url = urljoin(url, iframe["src"])

            # 3. iframe 내부 페이지 재요청
            inner_response = requests.get(
                inner_url,
                headers=HEADERS_FOR_CRAWLER,
                timeout=10
            )
            inner_response.raise_for_status()

            soup = BeautifulSoup(
                inner_response.text,
                "html.parser"
            )

        else:
            # iframe 없는 주소(PostView 등)는 현재 HTML 그대로 사용
            soup = outer_soup

        # 4. 최신 스마트에디터 본문 선택
        body_tag = soup.select_one("div.se-main-container")

        # 5. 구형 에디터 구조도 대비
        if body_tag is None:
            body_tag = soup.select_one("#postViewArea")

        if body_tag is None:
            print(f"본문 영역을 찾지 못함: {url}")
            return None

        print('네이버 블로그 본문 크롤링을 완료했습니다. ')
        
        num=rng.uniform(1,3)
        time.sleep(num)
        return body_tag.get_text(
            separator="\n",
            strip=True)
    
    except requests.RequestException as e:
        print(f"요청 오류: {url} / {e}")
        return None

In [ ]:
def main():
    try:
        df=blog_extractor()
        
        if df.empty:
            return df
        
        df['Content']=df['link'].apply(lambda x: body_text_extractor(x))
        
        return df
    except Exception as e:
        print(e)
        return df
    
    
    
if __name__=='__main__':
    df_samples=main()

블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.

In [37]:
df_samples

,title,link,postdate,keyword,Content
0,전자레인지용기 렌지쿡 간편하게 1인 간단한 즉석밥과 간단한요리,https://blog.naver.com/ppkj523/224440352656,20261013,신혼부부 필수템,​\n전자레인지용기로 간단하고 쉽게 요리가 가능한 렌지쿡 매직팟 1인가구나 자취용으...
1,테팔 세라믹 인덕션 냄비 두 가지 사이즈 써본 솔직 후기,https://blog.naver.com/al1gukne/224440352570,20261013,신혼부부 필수템,테팔 세라믹 인덕션 냄비 두 가지 사이즈 써본 솔직 후기\n​\n[2종세트] 테팔 ...
2,허리 통증 이제 안녕 세인트블랑 4단 황토 스펀지 매트리스 사용기,https://blog.naver.com/zxvmwztpgga/224440347306,20261013,신혼부부 필수템,허리 통증 이제 안녕 세인트블랑 4단 황토 스펀지 매트리스 사용기\n​\n허리에 좋...
3,LG 식기세척기 인덕션 실사용 후기 가격 고민 해결,https://blog.naver.com/xikxi5zqemaotju/2244403...,20261013,신혼부부 필수템,LG 식기세척기 인덕션 실사용 후기 가격 고민 해결\n​\nLG 디오스 오브제컬렉션...
4,로벤 2인용 식탁 직접 써본 솔직 사용기,https://blog.naver.com/dfo5g6a0jb/224440340670,20261013,신혼부부 필수템,로벤 2인용 식탁 직접 써본 솔직 사용기\n​\n로벤 2인용 포세린 세라믹 식탁 세...