Naver API
Client ID : 9q7w7kzlkz
Client Secret : 9oJbtNtakJ9vI2ipVbJkbco6YlJvorvzBF3nvUtG

In [101]:
import requests
import pandas as pd

In [102]:
API_URL = "https://naverapihub.apigw.ntruss.com/search/v1/blog"
CLIENT_ID='9q7w7kzlkz'
CLIENT_SECRET_KEY='9oJbtNtakJ9vI2ipVbJkbco6YlJvorvzBF3nvUtG'
headers={'X-NCP-APIGW-API-KEY-ID':CLIENT_ID,
         'X-NCP-APIGW-API-KEY':CLIENT_SECRET_KEY}
BATCH_SIZE=100
TARGET_NUMBER=1000
START_NUM=1
FORMAT='json'

검색어를 '신혼부부 필수템', '신혼부부 필수품', '신혼부부 강추템', '신혼부부 추천템' 등으로 구성되어 200개씩 생성

=> 검색어로 '직장인 필수품'을 선정하고, 관련 블로그 검색 시 어떤 상품이 가장 많이 언급되는 지를 알아보는 과정
=> 200개정도의 블로그 글이 대상

In [103]:
keywords=['신혼부부 필수템','신혼부부 필수품','신혼부부 강추템','신혼부부 추천템']

In [104]:
def blog_extractor(start_num, target_number, batch_size):
    data_dict={}
    
    for keyword in keywords:
        total_data=[]
        
        for start in range(start_num, target_number+1, batch_size):
            params={'query':keyword,
            'display':BATCH_SIZE,
            'start':start,
            'sort':'date',
            'format':FORMAT}

            try:
                response=requests.get(
                    API_URL,
                    headers=headers,
                    params=params,
                    timeout=15
                )
                response.raise_for_status()
                items=response.json().get('items',[])
                
                if not items:
                    break
                
                total_data.extend(items)                
            except Exception as e:
                print(e)
                break
        
        data_dict[keyword]=total_data

    return data_dict

In [105]:
blog_extractor=blog_extractor(START_NUM, TARGET_NUMBER, BATCH_SIZE)

In [106]:
df=pd.DataFrame({
    keyword:pd.Series(items)
    for keyword, items in blog_extractor.items()
})

# 결측값을 자동으로 대체하기 위해 Series를 사용함

In [119]:
df

,신혼부부 필수템,신혼부부 필수품,신혼부부 강추템,신혼부부 추천템
0,{'title': '오늘쓰임 편한 수기 가계부 <b>신혼부부</b> 가구의 예산 관...,{'title': '전국 웨딩 박람회 주말 일정 어디서 보나요? 스드메 다이렉트 견...,"{'title': 'W.<b>신혼</b>여행 _ 푸켓 (안다만 엠브레이스)', 'l...",{'title': '테팔 인덕션 티타늄 1X 델피니 프라이팬 직접 써보고 비교한 장...
1,"{'title': '집들이 선물 고를 때 실패 줄이는 실용 기준', 'link': ...","{'title': 'KWTUS7054F 밀레 와인셀러 추천, 와인맛을 지켜주는 수입...",{'title': '[<b>신혼</b>가전리뷰] LG전자 11개월 실사용 후기.. ...,"{'title': '탈취제인데 색감까지 예쁘네! 피에브 코튼 애프터 스프레이, 눈길..."
2,{'title': '2026 청년 전세대출 만 39세까지 확대｜2억·3억원 한도와 ...,{'title': '오늘쓰임 편한 수기 가계부 <b>신혼부부</b> 가구의 예산 관...,"{'title': '2026년 3분기 공병샷!', 'link': 'https://b...","{'title': '집들이 선물 고를 때 실패 줄이는 실용 기준', 'link': ..."
3,{'title': '커텐 셀프 설치 가성비 암막 쉬폰 커튼 실패 없는 초보자 커튼 ...,"{'title': '집들이 선물 고를 때 실패 줄이는 실용 기준', 'link': ...",{'title': '[LH 행복주택 36형] ep.7 11평 <b>신혼</b>집 주...,"{'title': '테팔 매직핸즈 인덕션 크렘 드 피치 5종 솔직 후기, 주방 수납..."
4,{'title': '26년 한일전자 BLDC 서큘레이터 LF200B 높이 조절 접이...,"{'title': '에어컨 렌탈 만기 인수형 총비용 비교 및 손해 안 보는 법', ...","{'title': '다이소 뷰티 꿀템 TOP3, 1천원 마스크팩부터 5천원 크림까지...",{'title': '광명 소하동 노브랜드 방문기｜주차부터 신상품·먹거리 가격까지 ....
...,...,...,...,...
995,"{'title': '실크핏 모던 반팔 반바지 커플 잠옷 솔직 사용기', 'link'...","{'title': '<b>신혼</b>집 인터넷 + TV 문의, 꼭 알아야 할 지식'...",NaN,"{'title': '프렘 더 슬림 음식물처리기 직접 써보니 삶의 질 달라졌어요', ..."
996,"{'title': '스윔어바웃 자외선차단모자 성인플랩캡, 여름 물놀이의 <b>필수<...",{'title': '2026 추석 선물세트 가성비 BEST 5! 3~5만원대 실속형...,NaN,"{'title': 'LG 트롬 오브제컬렉션 워시타워와 QNED TV 사용기', 'l..."
997,{'title': '캠핑 <b>필수템</b> 백년밥상 스지 바지락 전골 밀키트 맛있...,{'title': '거창 감악산 축제 아스타국화 꽃별여행 기간 셔틀버스 주차장 입장...,NaN,"{'title': '로보락 S8+ 사용 후기 가격 대비 최고의 선택', 'link'..."
998,"{'title': '비스포크 4도어 김치냉장고 490L 직접 써본 솔직 후기', '...",{'title': 'SMARTPET 더블 침대 전기 매트 겨울 추위 대비해 깔아본 ...,NaN,"{'title': '이노스 55인치 TV 써보니 삶의 질이 달라져요', 'link'..."
999,{'title': 'LG 디오스 오브제컬렉션 냉장고 3개월 써보니 삶의 질 상승했어...,"{'title': '신차 장기렌트카 견적,장단점 총정리(+인수 조건 세금)', 'l...",NaN,{'title': '누비아 NDW-NI6B 6인용 식기세척기 직접 써본 솔직 후기'...

In [120]:
df_sample1, df_sample2, df_sample3, df_sample4=(
    df['신혼부부 필수템'],
    df['신혼부부 필수품'],
    df['신혼부부 강추템'],
    df['신혼부부 추천템']
)

In [121]:
df_sample1.loc[:]

0      {'title': '오늘쓰임 편한 수기 가계부 <b>신혼부부</b> 가구의 예산 관...
1      {'title': '집들이 선물 고를 때 실패 줄이는 실용 기준', 'link': ...
2      {'title': '2026 청년 전세대출 만 39세까지 확대｜2억·3억원 한도와 ...
3      {'title': '커텐 셀프 설치 가성비 암막 쉬폰 커튼 실패 없는 초보자 커튼 ...
4      {'title': '26년 한일전자 BLDC 서큘레이터 LF200B 높이 조절 접이...
                             ...
995    {'title': '실크핏 모던 반팔 반바지 커플 잠옷 솔직 사용기', 'link'...
996    {'title': '스윔어바웃 자외선차단모자 성인플랩캡, 여름 물놀이의 <b>필수<...
997    {'title': '캠핑 <b>필수템</b> 백년밥상 스지 바지락 전골 밀키트 맛있...
998    {'title': '비스포크 4도어 김치냉장고 490L 직접 써본 솔직 후기', '...
999    {'title': 'LG 디오스 오브제컬렉션 냉장고 3개월 써보니 삶의 질 상승했어...
Name: 신혼부부 필수템, Length: 1000, dtype: object

In [122]:
def text_extractor(df):
    sample_df=pd.json_normalize(df.loc[:])
    sample_df.index=df.index
    return sample_df

In [133]:
samples=[df_sample1, df_sample2, df_sample3, df_sample4]

In [124]:
samples=[text_extractor(df) for df in samples]

In [127]:
df_sample1, df_sample2, df_sample3, df_sample4=samples

In [115]:
drop_cols=['bloggername','bloggerlink'] # 블로그 이름은 의미가 없고, description 대신 본문을 크롤링 할 것이기 때문에, 지움. bloggerlink도 의미 없음

In [134]:
samples=[df.drop(columns=drop_cols, axis=1) for df in samples]

# 윗 코드에서 inplace=True를 하지 않아도 되는 이유는, 삭제된 결과를 이미 samples에 다시 저장했기 때문이다.

In [137]:
import re

def txtcleaner(txt):
    if not isinstance(txt, str):
        return ""
    
    txt=re.sub(r'[^가-힣\s]',' ', txt) # 가-힣과 공백을 제외한 모든 문제 제거하는 메서드
    txt=re.sub(r'\s+',' ', txt).strip() # 연소 공백, 줄바꿈 등을 공백 하나로 정리
    return txt

In [138]:
target_col=['title','description']
for sample in samples:
    for target in target_col:
        sample[target]=sample[target].apply(txtcleaner)

In [139]:
df_sample1, df_sample2, df_sample3, df_sample4=samples

In [140]:
df_sample1

,title,link,description,postdate
0,오늘쓰임 편한 수기 가계부 신혼부부 가구의 예산 관리와 활용성 비,https://blog.naver.com/cmfnfh78/224429395351,신혼부부 의 필수템 가정 경제를 관리하는 것은 신혼부부 에게 중요한 일입니다 오늘쓰...,20261002
1,집들이 선물 고를 때 실패 줄이는 실용 기준,https://blog.naver.com/hye-milk/224429390766,어차피 매일 쓰는 필수템 이라서 받는 사람도 보관 부담이 덜해요 센스 집들이선물 신...,20261002
2,청년 전세대출 만 세까지 확대 억 억원 한도와 신청조건,https://blog.naver.com/jmt_2/224429135565,억원 신혼 유자녀 임차보증금의 이내 최대 억원 소득 연 만원 이하 신혼부부 부부 중...,20261002
3,커텐 셀프 설치 가성비 암막 쉬폰 커튼 실패 없는 초보자 커튼 시공,https://blog.naver.com/miiniiblog/224429186924,커튼 셀프 설치 필수 아이템과 꿀팁 목록은 맨 하단에 있으니 끝까지 읽어주세요 거실...,20261002
4,년 한일전자 서큘레이터 높이 조절 접이식 무선이라 거실,https://blog.naver.com/xghjq5nqq/224429351912,여름엔 필수 가전 겨울엔 순환가전으로 사계절 내내 열일하는 저의 좁은 공간을 넓게 ...,20261002
...,...,...,...,...
995,실크핏 모던 반팔 반바지 커플 잠옷 솔직 사용기,https://blog.naver.com/ax2xz4o26ye28n2/2244268...,여름 홈웨어 필수템 으로 완전 등극했습니다 가장 좋은 점은 역시 쾌적함이고 보너스로...,20260930
996,스윔어바웃 자외선차단모자 성인플랩캡 여름 물놀이의 필수 아이,https://blog.naver.com/hmenjo9oqy/224426845747,사실 여름이면 바닷가나 수영장에 자주 가는 저희 부부 에게 자외선 수영장 여름 필수...,20260930
997,캠핑 필수템 백년밥상 스지 바지락 전골 밀키트 맛있어요,https://blog.naver.com/87sudjd/224426844263,캠핑 필수템 이 밀키트는 캠핑에 정말 잘 어울리는 음식이라 추천하고 싶어요 다른 친...,20260930
998,비스포크 도어 김치냉장고 직접 써본 솔직 후기,https://blog.naver.com/j15t9qehecx2/224426844571,비염 있는 저에게는 정말 필수템 이에요 등급 에너지 효율로 전기세 걱정도 덜었어요 ...,20260930
999,디오스 오브제컬렉션 냉장고 개월 써보니 삶의 질 상승했어요,https://blog.naver.com/e2b431mesxp2/224426842927,특히 여름철에 냉장고 많이 쓰는데 이 부분은 정말 칭찬해주고 원하는 신혼부부 나 가...,20260930

In [146]:
# 블로그 HTML 구조를 파악한 뒤에 차례로 크롤링 해야 함
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time
import numpy as np
body_data=[]

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36"
    )
}
def body_text_extractor(url):
    print('블로그 본문을 수집합니다.')
    
    rng = np.random.default_rng()

    
    
    try:
        # 1. 외부 네이버 블로그 페이지 요청
        response = requests.get(
            url,
            headers=HEADERS,
            timeout=10
        )
        
        response.raise_for_status()

        outer_soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # 2. 실제 본문을 담은 iframe 주소 찾기
        iframe = outer_soup.select_one("iframe#mainFrame")

        if iframe is not None and iframe.get("src"):
            inner_url = urljoin(url, iframe["src"])

            # 3. iframe 내부 페이지 재요청
            inner_response = requests.get(
                inner_url,
                headers=HEADERS,
                timeout=10
            )
            inner_response.raise_for_status()

            soup = BeautifulSoup(
                inner_response.text,
                "html.parser"
            )

        else:
            # iframe 없는 주소(PostView 등)는 현재 HTML 그대로 사용
            soup = outer_soup

        # 4. 최신 스마트에디터 본문 선택
        body_tag = soup.select_one("div.se-main-container")

        # 5. 구형 에디터 구조도 대비
        if body_tag is None:
            body_tag = soup.select_one("#postViewArea")

        if body_tag is None:
            print(f"본문 영역을 찾지 못함: {url}")
            return None

        print('네이버 블로그 본문 크롤링을 완료했습니다. ')
        
        num=rng.uniform(1,3)
        time.sleep(num)
        return body_tag.get_text(
            separator="\n",
            strip=True)
    
    except requests.RequestException as e:
        print(f"요청 오류: {url} / {e}")
        return None

html에서 iframe 구조는 HTML 페이지 안에서 다른 웹 문서나 외부 서비스를 작은 독립 창처럼 삽입하기 위해서 쓰는 것으로, 다른페이지를 직접 구현하지 않고 가져와서 보여주기 위함
네이버 블로그의 맥락에서는 서비스에서 공통으로 활용하는 툴과, 실제 게시글 콘텐츠를 분리하기 위함

In [147]:
df_sample1['content']=df_sample1['link'].apply(body_text_extractor)

블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.

KeyboardInterrupt:

In [14]:
df_sample['content']=df_sample['link'].apply(lambda x: body_text_extractor(x))

블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.

In [15]:
df_sample['content_cleaned']=df_sample['content'].apply(lambda x: txtcleaner(x))

In [16]:
df_sample

,title,link,postdate,content,content_cleaned
0,무선 이어폰 소니 블랙 최저가 비교부터 노이즈캔슬링 성능,https://blog.naver.com/bboksunga/224426002746,20260929,​\n​\n출퇴근길 대중교통 소음이나 카페의 시끄러운 백색소음 속에서 온전히 음악에...,출퇴근길 대중교통 소음이나 카페의 시끄러운 백색소음 속에서 온전히 음악에 집중하고 ...
1,대학생 직장인 태블릿 추천 필기 영상 시청 작업용도에 맞는 아,https://blog.naver.com/forevertrb/224425734031,20260929,"스마트폰보다 시원한 대화면, 노트북보다 가벼운 휴대성으로 대학생과 직장인 모두에게 ...",스마트폰보다 시원한 대화면 노트북보다 가벼운 휴대성으로 대학생과 직장인 모두에게 필...
2,꿈찾는 곰 젖병 아기의 수유습관을 지키기 위한 구성품 정보,https://blog.naver.com/gutsusetsu198427/224425...,20260929,"이 글에는 쇼핑 커넥트 상품이 포함되어 있으며,\n판매 발생시 크리에이터는 수수료를...",이 글에는 쇼핑 커넥트 상품이 포함되어 있으며 판매 발생시 크리에이터는 수수료를 받...

In [ ]:
df['content']=df['link'].apply(lambda x: body_text_extractor(x))