활용 분석 방법 : 소셜 데이터, ML, DL(?), EDA, NLP, LLM 등 활용
주요 데이터 : 정형데이터를 확보하기 어려우므로, 소셜데이터를 주로 활용예정, API를 활용해 데이터를 끌어올 수도 있음
타겟 사이트 : 커뮤니티, 유튜브,,? 등 소셜 데이터 최대한 활용
주제 : 사회현상?, 소비현상? 등을 기반으로 이야기를 전개해 나감
블로그, 커뮤니티 등에서 뭔가를 얻을 수 있을 거 같은데.... 본문 댓글을 LLM에 보내서, 데이터 라벨링을 얻는다.?

1. 소셜 채널로서 블로그의 특성은?
- 개인의 체험기, 긍/부정이 명확하게 드러남
- 협찬 가능성을 배제할 수 없음 (무조건적인 긍정)
- X를 포함한 SNS의 크롤링이 어려운 상황에서, 소비자의 추이를 파악하기 용이한 채널

2. 무엇을 얻을 것인가?
- 특정 상품과 관련하여 최근 소비자의 트렌드가 어떠한지? (어떤 상품을 고를 것인지가 중요)
- 형태소 분리를 통한 단순 언급량 계산에서 한발 더 나아가, LLM 활용 방식을 고민해야 함
- 대분류 -> 중분류 -> 상품 타겟팅의 방식으로 가야 함
ㄴ 최근 특정 산업 분야(대·중분류)에서 유행하는 상품을 추린 뒤에 -> 상품을 타겟팅 하는 방식으로 이동

=> '직장인 필수품', '신혼부부 필수품' 이런 식으로 라이프스타일을 설정한 뒤에 필요한 물품을 추리는 방식은 어떨까?
-> 현재는 이 방식이 가장 유력함

3. 판단 기준
- LLM이 판단할 수 있는 기준을 마련해줘야 함. 단순히 몇 줄짜리 쓰는 거에서 나아가서 명확하게 1/0 데이터를 넣어줘야 함

Naver API
Client ID : 9q7w7kzlkz
Client Secret : 9oJbtNtakJ9vI2ipVbJkbco6YlJvorvzBF3nvUtG

In [ ]:
import requests
import pandas as pd

In [2]:
API_URL = "https://naverapihub.apigw.ntruss.com/search/v1/blog"
CLIENT_ID='9q7w7kzlkz'
CLIENT_SECRET_KEY='9oJbtNtakJ9vI2ipVbJkbco6YlJvorvzBF3nvUtG'
headers={'X-NCP-APIGW-API-KEY-ID':CLIENT_ID,
         'X-NCP-APIGW-API-KEY':CLIENT_SECRET_KEY}
BATCH_SIZE=100
TARGET_NUMBER=200
START_NUM=1
FORMAT='json'

검색어를 '신혼부부 필수템', '신혼부부 필수품', '신혼부부 강추템', '신혼부부 추천템' 등으로 구성되어 200개씩 생성

=> 검색어로 '직장인 필수품'을 선정하고, 관련 블로그 검색 시 어떤 상품이 가장 많이 언급되는 지를 알아보는 과정
=> 200개정도의 블로그 글이 대상

In [ ]:
keywords=['신혼부부 필수템','신혼부부 필수품','신혼부부 강추템','신혼부부 추천템']

In [4]:
def blog_extractor(start_num, target_number, batch_size):
    data_dict={}
    
    for keyword in keywords:
        total_data=[]
        
        for start in range(start_num, target_number+1, batch_size):
            params={'query':keyword,
            'display':BATCH_SIZE,
            'start':start,
            'sort':'date',
            'format':FORMAT}

            try:
                response=requests.get(
                    API_URL,
                    headers=headers,
                    params=params,
                    timeout=15
                )
                response.raise_for_status()
                items=response.json().get('items',[])
                
                if not items:
                    break
                
                total_data.extend(items)                
            except Exception as e:
                print(e)
                break
        
        data_dict[keyword]=total_data

    return data_dict

In [5]:
blog_extractor=blog_extractor(START_NUM, TARGET_NUMBER, BATCH_SIZE)

In [ ]:
df=pd.DataFrame({
    keyword:pd.Series(items)
    for keyword, items in blog_extractor.items()
})

# 결측값을 자동으로 대체하기 위해 Series를 사용함

In [7]:
df_sample1, df_sample2, df_sample3, df_sample4=(
    df['신혼부부 필수템'],
    df['신혼부부 필수품'],
    df['신혼부부 강추템'],
    df['신혼부부 추천템']
)

In [8]:
df_sample1.loc[:]

0      {'title': '<b>신혼부부 필수템</b> 휴롬 착즙기 H420 써보니', '...
1      {'title': 'bange 남자 여행용 백팩 캐리어 결합, <b>신혼부부</b>...
2      {'title': '<b>신혼부부</b> 및 3인가구 <b>필수템</b>, 삼성 비...
3      {'title': '<b>신혼부부</b>의 <b>필수템</b>! 벨라 무헤드 토퍼프...
4      {'title': '삼성 비스포크 식기세척기 추천 후기｜<b>신혼부부</b> 자취생...
                             ...
195    {'title': '여름잠옷 <b>필수템</b> 커플잠옷 세트 민티 반팔 카라로 <...
196    {'title': '원룸 자취 <b>필수템</b>, 디베아 차이슨 무선 청소기 써보...
197    {'title': '<b>신혼부부</b> 집들이 <b>필수템</b> - 더함 편백찜...
198    {'title': '혼수 <b>필수템</b>! 오브 6인 무광 그릇세트로 <b>신혼...
199    {'title': '가사 노동은 반으로 줄이고 만족도는 두 배로 높이는 <b>신혼부...
Name: 신혼부부 필수템, Length: 200, dtype: object

In [9]:
print(pd.__version__)

2.3.3

In [10]:
sample_df=pd.json_normalize(df_sample1.loc[:])
sample_df.index=df_sample1.index

In [ ]:
def text_extractor(df):
    sample_df=pd.json_normalize(df.loc[:])
    sample_df.index=df.index
    return sample_df

In [13]:
df_sample1=text_extractor(df_sample1)

In [14]:
df_sample1

,title,link,description,bloggername,bloggerlink,postdate
0,<b>신혼부부 필수템</b> 휴롬 착즙기 H420 써보니,https://blog.naver.com/8hyhy/224426097116,간편해서 <b>신혼부부</b>나 건강식에 관심 있는 사람에게 딱일 것 같아요. 다양...,브라운자의주식일기,https://blog.naver.com/8hyhy,20260929
1,"bange 남자 여행용 백팩 캐리어 결합, <b>신혼부부</b>의 스마트한 일상 <...",https://blog.naver.com/zwjodpfem/224425769957,평소 <b>신혼</b>생활을 하면서 짐을 꾸리거나 이동할 일이 많아 불편함을 느끼던...,복실식빵연구원,https://blog.naver.com/zwjodpfem,20260929
2,"<b>신혼부부</b> 및 3인가구 <b>필수템</b>, 삼성 비스포크 6인용 식기세...",https://blog.naver.com/kinjhee/224425298875,직접 비교해 본 설치와 크기 기준 타사 미니 식기세척기들과 비교했을 때 가장 중요하...,쇼핑노트 엔터테이먼트,https://blog.naver.com/kinjhee,20260929
3,<b>신혼부부</b>의 <b>필수템</b>! 벨라 무헤드 토퍼프레임으로 편안한 잠자...,https://blog.naver.com/uebkt8ro/224425564534,오늘은 제가 최근에 구매한 벨라 무헤드 토퍼프레임 <b>신혼부부</b>... <b>...,순한 바질 안내자,https://blog.naver.com/uebkt8ro,20260929
4,삼성 비스포크 식기세척기 추천 후기｜<b>신혼부부</b> 자취생 <b>필수템</b>...,https://blog.naver.com/iop70330/224425040362,혼자 살거나 <b>신혼</b>이면 설거지 시간 아낄 방법 찾다가 여기까지 오는 경우...,언니의 추천,https://blog.naver.com/iop70330,20260929
...,...,...,...,...,...,...
195,여름잠옷 <b>필수템</b> 커플잠옷 세트 민티 반팔 카라로 <b>신혼부부</b>의...,https://blog.naver.com/tidhjowi372/224391493337,"게다가, <b>신혼부부</b>잠옷으로도 추천받는 제품이라 서로 맞춰 입으면 정말 귀...",tidhjowi372님의 블로그,https://blog.naver.com/tidhjowi372,20260827
196,"원룸 자취 <b>필수템</b>, 디베아 차이슨 무선 청소기 써보니 이 가격에 이 ....",https://blog.naver.com/eugene9851/224391338638,"me 요즘 자취방이나 원룸 사시는 분들, 혹은 <b>신혼부부</b> 분들 청소기 하...",딩IT로그,https://blog.naver.com/eugene9851,20260826
197,<b>신혼부부</b> 집들이 <b>필수템</b> - 더함 편백찜기 내돈내산 솔직후기...,https://blog.naver.com/ddu_ddin/224391298349,바로 <b>신혼</b>집을 준비하면서 꼭! 사고싶었던 '더함 편백찜기' 사실 부모님...,SOOSOO한 일상,https://blog.naver.com/ddu_ddin,20260826
198,혼수 <b>필수템</b>! 오브 6인 무광 그릇세트로 <b>신혼</b> 주방을 우아...,https://blog.naver.com/takmi0316/224390403546,왠지 모르게 <b>신혼</b>집 분위기가 살아나는 느낌이에요. 왠지 모르게 손님.....,스티븐 잡화신잡,https://blog.naver.com/takmi0316,20260826
199,가사 노동은 반으로 줄이고 만족도는 두 배로 높이는 <b>신혼부부</b> 혼수....,https://blog.naver.com/neatcive/224390541233,"<b>신혼</b>의 달콤함도 잠시, 쏟아지는 집안일 앞에 서로 예민해져 다투는 일도...",neatcive의 일상을 바꾸는 아이템,https://blog.naver.com/neatcive,20260826

In [8]:
import re

def txtcleaner(txt):
    if not isinstance(txt, str):
        return ""
    
    txt=re.sub(r'[^가-힣\s]',' ', txt) # 가-힣과 공백을 제외한 모든 문제 제거하는 메서드
    txt=re.sub(r'\s+',' ', txt).strip() # 연소 공백, 줄바꿈 등을 공백 하나로 정리
    return txt
target_col=['title','description']
for col in target_col:
    df[col]=df[col].apply(txtcleaner)

In [9]:
drop_cols=['bloggername','description','bloggerlink'] # 블로그 이름은 의미가 없고, description 대신 본문을 크롤링 할 것이기 때문에, 지움. bloggerlink도 의미 없음
df=df.drop(columns=drop_cols)

In [10]:
df

,title,link,postdate
0,무선 이어폰 소니 블랙 최저가 비교부터 노이즈캔슬링 성능,https://blog.naver.com/bboksunga/224426002746,20260929
1,대학생 직장인 태블릿 추천 필기 영상 시청 작업용도에 맞는 아,https://blog.naver.com/forevertrb/224425734031,20260929
2,꿈찾는 곰 젖병 아기의 수유습관을 지키기 위한 구성품 정보,https://blog.naver.com/gutsusetsu198427/224425...,20260929
3,제목 가성비 태블릿 추천 년 대학생 인강 필기용 용도별 사양,https://blog.naver.com/jyp940106/224425093989,20260928
4,제목 년 가성비 노트북 추천 직장인 대학생을 위한 용도별 고,https://blog.naver.com/jyp940106/224425091851,20260928
...,...,...,...
995,여행 필수품 바우아토 가벼운 보조배터리 왜 써야 할까,https://blog.naver.com/jk0918/224335694882,20260705
996,구글 제미나이 유료 프로 가격 싸게 이용하는 방법,https://blog.naver.com/lth0713/224336537762,20260704
997,매번 품절 대란 밥클럽 아침밥 할인으로 쟁여두기 인증,https://blog.naver.com/klsaska/224336525851,20260704
998,직장인 하루루틴의 필수품 루업 굿데이 세트,https://blog.naver.com/juvenile20/224336335900,20260704
999,그램 코어 세대 램 단품 단품,https://blog.naver.com/enscq14298/224335442251,20260704

In [12]:
# 블로그 HTML 구조를 파악한 뒤에 차례로 크롤링 해야 함
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time
body_data=[]

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36"
    )
}
def body_text_extractor(url):
    print('블로그 본문을 수집합니다.')
    try:
        # 1. 외부 네이버 블로그 페이지 요청
        response = requests.get(
            url,
            headers=HEADERS,
            timeout=10
        )
        
        response.raise_for_status()

        outer_soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # 2. 실제 본문을 담은 iframe 주소 찾기
        iframe = outer_soup.select_one("iframe#mainFrame")

        if iframe is not None and iframe.get("src"):
            inner_url = urljoin(url, iframe["src"])

            # 3. iframe 내부 페이지 재요청
            inner_response = requests.get(
                inner_url,
                headers=HEADERS,
                timeout=10
            )
            inner_response.raise_for_status()

            soup = BeautifulSoup(
                inner_response.text,
                "html.parser"
            )

        else:
            # iframe 없는 주소(PostView 등)는 현재 HTML 그대로 사용
            soup = outer_soup

        # 4. 최신 스마트에디터 본문 선택
        body_tag = soup.select_one("div.se-main-container")

        # 5. 구형 에디터 구조도 대비
        if body_tag is None:
            body_tag = soup.select_one("#postViewArea")

        if body_tag is None:
            print(f"본문 영역을 찾지 못함: {url}")
            return None

        print('네이버 블로그 본문 크롤링을 완료했습니다. ')
        
        time.sleep(3)
        return body_tag.get_text(
            separator="\n",
            strip=True)
    
    except requests.RequestException as e:
        print(f"요청 오류: {url} / {e}")
        return None

html에서 iframe 구조는 HTML 페이지 안에서 다른 웹 문서나 외부 서비스를 작은 독립 창처럼 삽입하기 위해서 쓰는 것으로, 다른페이지를 직접 구현하지 않고 가져와서 보여주기 위함
네이버 블로그의 맥락에서는 서비스에서 공통으로 활용하는 툴과, 실제 게시글 콘텐츠를 분리하기 위함

In [13]:
df_sample=df.iloc[:3,:].copy()

In [14]:
df_sample['content']=df_sample['link'].apply(lambda x: body_text_extractor(x))

블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.

In [15]:
df_sample['content_cleaned']=df_sample['content'].apply(lambda x: txtcleaner(x))

In [16]:
df_sample

,title,link,postdate,content,content_cleaned
0,무선 이어폰 소니 블랙 최저가 비교부터 노이즈캔슬링 성능,https://blog.naver.com/bboksunga/224426002746,20260929,​\n​\n출퇴근길 대중교통 소음이나 카페의 시끄러운 백색소음 속에서 온전히 음악에...,출퇴근길 대중교통 소음이나 카페의 시끄러운 백색소음 속에서 온전히 음악에 집중하고 ...
1,대학생 직장인 태블릿 추천 필기 영상 시청 작업용도에 맞는 아,https://blog.naver.com/forevertrb/224425734031,20260929,"스마트폰보다 시원한 대화면, 노트북보다 가벼운 휴대성으로 대학생과 직장인 모두에게 ...",스마트폰보다 시원한 대화면 노트북보다 가벼운 휴대성으로 대학생과 직장인 모두에게 필...
2,꿈찾는 곰 젖병 아기의 수유습관을 지키기 위한 구성품 정보,https://blog.naver.com/gutsusetsu198427/224425...,20260929,"이 글에는 쇼핑 커넥트 상품이 포함되어 있으며,\n판매 발생시 크리에이터는 수수료를...",이 글에는 쇼핑 커넥트 상품이 포함되어 있으며 판매 발생시 크리에이터는 수수료를 받...

In [ ]:
df['content']=df['link'].apply(lambda x: body_text_extractor(x))