활용 분석 방법 : 소셜 데이터, ML, DL(?), EDA, NLP, LLM 등 활용
주요 데이터 : 정형데이터를 확보하기 어려우므로, 소셜데이터를 주로 활용예정, API를 활용해 데이터를 끌어올 수도 있음
타겟 사이트 : 커뮤니티, 유튜브,,? 등 소셜 데이터 최대한 활용
주제 : 사회현상?, 소비현상? 등을 기반으로 이야기를 전개해 나감
블로그, 커뮤니티 등에서 뭔가를 얻을 수 있을 거 같은데.... 본문 댓글을 LLM에 보내서, 데이터 라벨링을 얻는다.?

1. 소셜 채널로서 블로그의 특성은?
- 개인의 체험기, 긍/부정이 명확하게 드러남
- 협찬 가능성을 배제할 수 없음 (무조건적인 긍정)
- X를 포함한 SNS의 크롤링이 어려운 상황에서, 소비자의 추이를 파악하기 용이한 채널

2. 무엇을 얻을 것인가?
- 특정 상품과 관련하여 최근 소비자의 트렌드가 어떠한지? (어떤 상품을 고를 것인지가 중요)
- 형태소 분리를 통한 단순 언급량 계산에서 한발 더 나아가, LLM 활용 방식을 고민해야 함
- 대분류 -> 중분류 -> 상품 타겟팅의 방식으로 가야 함
ㄴ 최근 특정 산업 분야(대·중분류)에서 유행하는 상품을 추린 뒤에 -> 상품을 타겟팅 하는 방식으로 이동

=> '직장인 필수품', '신혼부부 필수품' 이런 식으로 라이프스타일을 설정한 뒤에 필요한 물품을 추리는 방식은 어떨까?
-> 현재는 이 방식이 가장 유력함

3. 판단 기준
- LLM이 판단할 수 있는 기준을 마련해줘야 함. 단순히 몇 줄짜리 쓰는 거에서 나아가서 명확하게 1/0 데이터를 넣어줘야 함

Naver API
Client ID : 9q7w7kzlkz
Client Secret : 9oJbtNtakJ9vI2ipVbJkbco6YlJvorvzBF3nvUtG

In [1]:
import requests
import pandas as pd

In [3]:
API_URL = "https://naverapihub.apigw.ntruss.com/search/v1/blog"
CLIENT_ID='9q7w7kzlkz'
CLIENT_SECRET_KEY='9oJbtNtakJ9vI2ipVbJkbco6YlJvorvzBF3nvUtG'
headers={'X-NCP-APIGW-API-KEY-ID':CLIENT_ID,
         'X-NCP-APIGW-API-KEY':CLIENT_SECRET_KEY}
BATCH_SIZE=100
TARGET_NUMBER=200
START_NUM=1
FORMAT='json'

검색어를 '신혼부부 필수템', '신혼부부 필수품', '신혼부부 강추템', '신혼부부 추천템' 등으로 구성되어 200개씩 생성

=> 검색어로 '직장인 필수품'을 선정하고, 관련 블로그 검색 시 어떤 상품이 가장 많이 언급되는 지를 알아보는 과정
=> 200개정도의 블로그 글이 대상

In [4]:
keywords=['신혼부부 필수템','신혼부부 필수품','신혼부부 강추템','신혼부부 추천템']

In [13]:
def blog_extractor(start_num, target_number, batch_size):
    data_dict={}
    
    for keyword in keywords:
        total_data=[]
        
        for start in range(start_num, target_number+1, batch_size):
            params={'query':keyword,
            'display':BATCH_SIZE,
            'start':start,
            'sort':'date',
            'format':FORMAT}

            try:
                response=requests.get(
                    API_URL,
                    headers=headers,
                    params=params,
                    timeout=15
                )
                response.raise_for_status()
                items=response.json().get('items',[])
                
                if not items:
                    break
                
                total_data.extend(items)                
            except Exception as e:
                print(e)
                break
        
        data_dict[keyword]=total_data

    return data_dict

In [14]:
blog_extractor=blog_extractor(START_NUM, TARGET_NUMBER, BATCH_SIZE)

In [15]:
len(blog_extractor)

4

In [ ]:
blog_extractorw

{'신혼부부 필수템': [{'title': 'bange 남자 여행용 백팩 캐리어 결합, <b>신혼부부</b>의 스마트한 일상 <b>필수</b>....',
   'link': 'https://blog.naver.com/zwjodpfem/224425769957',
   'description': '평소 <b>신혼</b>생활을 하면서 짐을 꾸리거나 이동할 일이 많아 불편함을 느끼던 차에 이 백팩을 발견했어요.... bange 남자 여행용 백팩 캐리어 결합, <b>신혼부부</b>의 스마트한 일상 <b>필수템</b> <b>신혼부부</b>인 저희는 주말마다... ',
   'bloggername': '복실식빵연구원',
   'bloggerlink': 'https://blog.naver.com/zwjodpfem',
   'postdate': '20260929'},
  {'title': '<b>신혼부부</b> 및 3인가구 <b>필수템</b>, 삼성 비스포크 6인용 식기세척기 카운....',
   'link': 'https://blog.naver.com/kinjhee/224425298875',
   'description': '직접 비교해 본 설치와 크기 기준 타사 미니 식기세척기들과 비교했을 때 가장 중요하게 본 부분은... 이 제품은 일반적인 3인가구 기준이나 <b>신혼부부</b> 집에서 상판 타공을 최소화하거나 무타공으로도 비교적... ',
   'bloggername': '쇼핑노트 엔터테이먼트',
   'bloggerlink': 'https://blog.naver.com/kinjhee',
   'postdate': '20260929'},
  {'title': '<b>신혼부부</b>의 <b>필수템</b>! 벨라 무헤드 토퍼프레임으로 편안한 잠자리를 ....',
   'link': 'https://blog.naver.com/uebkt8ro/224425564534',
   'description': '오늘은 제가 최근에 구매한 벨라 무헤드 토퍼프레임 <b>신혼부부</b>... <b>부부</b>침대 #수면환경 #내구성좋은제품 #깔끔한인테리어 #편안한수면 #실용적인침대 #추천제품 #가성비좋은침대 #<b>신혼</b>가전 #생활<b>필수템</b>... ',
   'bloggername': '순한 바질 안내자',
   'bloggerlink': 'https://blog.naver.com/uebkt8ro',
   'postdate': '20260929'},
  {'title': '삼성 비스포크 식기세척기 추천 후기｜<b>신혼부부</b> 자취생 <b>필수템</b> 꿀....',
   'link': 'https://blog.naver.com/iop70330/224425040362',
   'description': '혼자 살거나 <b>신혼</b>이면 설거지 시간 아낄 방법 찾다가 여기까지 오는 경우 많잖아요. &quot;젖병 소독까지... 이 부분에서 확실히 유리함. ② 젖병·식기 소독 기능 지원 <b>신혼부부</b>·초보부모 타깃 위생 관리 니즈 충족... ',
   'bloggername': '언니의 추천',
   'bloggerlink': 'https://blog.naver.com/iop70330',
   'postdate': '20260929'},
  {'title': 'N개월 써보니 주방 <b>필수템</b> 등극한 대웅 모닝컴 밥솥 3인용 4인용',
   'link': 'https://blog.naver.com/eaooqfybw/224425456738',
   'description': '저처럼 1인 가구나 <b>신혼부부</b>, 혹은 밥솥 하나 더 두고 싶은 분들께... 특히 맞벌이 <b>부부</b>나 1인 가구에게는 정말 최고의 선택이 될 거예요. 2.... 주방인테리어 #<b>신혼</b>밥솥 #1인용밥솥 #주부<b>필수템</b> #밥솥추천... ',
   'bloggername': 'eaooqfybw님의 블로그',
   'bloggerlink': 'https://blog.naver.com/eaooqfybw',
   'postdate': '20260929'},
  {'title': '솔러스에어 탁상용선풍기 3개월 써보니 여름 <b>필수템</b>! USB 무선 선풍....',
   'link': 'https://blog.naver.com/yckffj5bvnw/224425415591',
   'description': '저처럼 자취하시는 분들, <b>신혼부부</b>, 1인 가구라면 제 말에 완전 공감하실 거예요. 왜 키친아트 3인용... 캠핑 <b>필수템</b>! 이게 제일 마음에 드는 부분인데요. USB 충전이라 보조배터리에 연결해서 캠핑 갈 때나 차... ',
   'bloggername': 'yckffj5bvnw님의 블로그',
   'bloggerlink': 'https://blog.naver.com/yckffj5bvnw',
   'postdate': '20260929'},
  {'title': '테팔 미니밥솥 팝솥 소형 전기밥솥 2인용 솥밥 RK535 민트 : 테팔, 똑....',
   'link': 'https://blog.naver.com/hi_robo_/224422068391',
   'description': '아닌 <b>필수템</b>이 되어가고 있어요. 특히 디자인과 성능을 모두 잡은... 매력적인 부분일 것입니다. 테팔 미니밥솥 RK535, 이런 분들께 추천해요! 1인 가구 또는 <b>신혼부부</b>: 두 사람이 먹기 좋은 양의 밥을 갓 지어... ',
   'bloggername': '로보맘대로',
   'bloggerlink': 'https://blog.naver.com/hi_robo_',
   'postdate': '20260928'},
  {'title': '<b>신혼부부</b> 임신준비 <b>필수템</b>! 스마일 배란기테스트기 내돈내산 솔직 ....',
   'link': 'https://blog.naver.com/ddj04323/224424931089',
   'description': '<b>신혼부부</b> 임신준비 <b>필수템</b>! 스마일 배란기테스트기 내돈내산 솔직 후기(브랜드 비교 &amp; 실사용 앱 연동)... 보통 <b>부부</b>들이 숙제를 한다고 하더라구요 ㅎㅎ 4. 마무리 저희는 <b>신혼</b> 1년 차는 둘만의 시간도 신나게... ',
   'bloggername': '쥬쥬랜드의 우당팅탕 기록지',
   'bloggerlink': 'https://blog.naver.com/ddj04323',
   'postdate': '20260928'},
  {'title': '자취생 <b>필수템</b>! 키친아트 3인용 밥솥으로 집밥 퀄리티 UP',
   'link': 'https://blog.naver.com/nxuzzgnx/224424361384',
   'description': '1인 가구든 <b>신혼부부</b>든, 자취방 원룸에 딱 맞는 사이즈라 강력... 분 ✅ <b>신혼부부</b> 집밥을 위한 실용적인 아이템을 찾는 분 ✅ 이유식이나... 1인가구밥솥 #<b>신혼부부</b>밥솥 #집밥 #이유식밥솥 #죽밥솥 #밥솥추천... ',
   'bloggername': 'nxuzzgnx님의 블로그',
   'bloggerlink': 'https://blog.naver.com/nxuzzgnx',
   'postdate': '20260928'},
  {'title': '키친아트 3인용 4인용 미니 소형 전기 압력기능 밥솥 밥통 이유식 자....',
   'link': 'https://blog.naver.com/eaooqfybw/224424347730',
   'description': '1인 가구나 <b>신혼부부</b>에게는 완전 <b>필수템</b>이에요. 자취생 <b>필수템</b>으로 강력 추천드려요! 왜 키친아트 미니 밥솥을 찾게 되었나? 솔직히 말하면, 처음에는 밥솥이 다 거기서 거기겠지 싶었어요. 그런데 혼자 살다... ',
   'bloggername': 'eaooqfybw님의 블로그',
   'bloggerlink': 'https://blog.naver.com/eaooqfybw',
   'postdate': '20260928'},
  {'title': 'LG 코드제로 오브제컬렉션 A9S + LG 디오스 인덕션 AI927WA BEI3QLOE <b>신혼</b>부....',
   'link': 'https://blog.naver.com/t0ngszwrlt/224424331799',
   'description': '특히 <b>신혼</b>집 <b>필수템</b>으로 완전 강추하는 조합이랍니다. 말 다 했죠? 왜 이 조합을 찾게 되었나? 결혼... 분 ☑️ <b>신혼</b>집 <b>필수</b> 가전으로 고급스러운 아이템을 찾는 분 ☑️ 요리 시간을 단축하고 싶은 워킹맘... ',
   'bloggername': 't0ngszwrlt님의 블로그',
   'bloggerlink': 'https://blog.naver.com/t0ngszwrlt',
   'postdate': '20260928'},
  {'title': '✨<b>신혼부부 필수템</b>! 삼성 키친핏 푸드쇼케이스 냉장고 RM70F63M2Z RK70F4....',
   'link': 'https://blog.naver.com/nwyub9whxmdq/224424259555',
   'description': '이사나 <b>신혼</b> 혼수로 가성비 좋은 대용량 냉장고를 찾는 분 ☑ 김치 보관 공간까지 넉넉한 프리미엄... 혼수가전 #<b>신혼부부필수템</b> #주방인테리어 #냉장고후기 #비스포크냉장고 #삼성전자 #가전제품 #주방가전... ',
   'bloggername': 'nwyub9whxmdq님의 블로그',
   'bloggerlink': 'https://blog.naver.com/nwyub9whxmdq',
   'postdate': '20260928'},
  {'title': '원룸 살이 <b>필수템</b>! 포쿨 미니냉동고 62L 덕분에 냉장고 공간 해방했....',
   'link': 'https://blog.naver.com/nxuzzgnx/224424254091',
   'description': '#포쿨 미니냉동고 #미니냉동고 #소형냉동고 #62L냉동고 #가정용냉동고 #원룸냉동고 #업소용냉동고 #슬림핏냉동고 #급속냉동 #냉동식품보관 #밀키트보관 #아이스크림보관 #주방가전 #1인 가구 <b>필수템</b> #<b>신혼부부</b>... ',
   'bloggername': 'nxuzzgnx님의 블로그',
   'bloggerlink': 'https://blog.naver.com/nxuzzgnx',
   'postdate': '20260928'},
  {'title': '캐치웰 스팀청소기 추천 <b>신혼부부</b> 아기 키우는 집 바닥청소 <b>필수템</b>',
   'link': 'https://blog.naver.com/yujin946/224424184735',
   'description': '캐치웰 스팀청소기 추천 <b>신혼부부</b> 아기 키우는 집 바닥청소 <b>필수템</b> 아기가 점점 크면서 요즘 집에서... 가장 마음에 들었던 건 빠른 예열 제가 캐치웰 스티미를 사용하면서 가장 마음에 들었던 부분은 바로... ',
   'bloggername': '한의사 새댁의 이모저모 life',
   'bloggerlink': 'https://blog.naver.com/yujin946',
   'postdate': '20260927'},
  {'title': '[강력추천 음식물처리기] <b>신혼부부 필수템</b> 남편들의 아이템 미닉스 ....',
   'link': 'https://blog.naver.com/reviewer216/224423915845',
   'description': '<b>신혼</b> 6개월차 남편의 강력 추천 <b>필수템</b>! 미닉스 음식물처리기입니다. 왜 강력 추천하나요? <b>신혼부부</b>들은 공감하시겠지만, 외식을 하지 않고 배달시켜먹거나, 요리를 해먹으면 음식물 쓰레기가 생각보다 많이... ',
   'bloggername': '재태크 , 상품 리뷰 , 경제 상식',
   'bloggerlink': 'https://blog.naver.com/reviewer216',
   'postdate': '20260927'},
  {'title': '아가드 무소음 유아 변기커버로 배변훈련 한번에 해결하기',
   'link': 'https://blog.naver.com/deadue64/224423769221',
   'description': "<b>신혼부부</b>의 배변훈련 <b>필수템</b> 요즘 아이가 배변훈련을 시작하면서 변기커버가 필요했거든요. 그래서 아가드 무소음 유아 변기커버를 구매했는데, 성인도 사용할 수 있어서 더 좋더라고요. 처음에는 '왜 이걸 사야... ",
   'bloggername': '나무랑놀기',
   'bloggerlink': 'https://blog.naver.com/deadue64',
   'postdate': '20260927'},
  {'title': '<b>신혼부부</b>에게 딱인 모달 원피스잠옷, 커플잠옷 세트 후기',
   'link': 'https://blog.naver.com/tt8u7u/224423336533',
   'description': '<b>신혼</b> <b>필수템</b> 소개 요즘 <b>신혼부부</b>들이 많이 찾는 커플잠옷 세트를 구매했어요. 원피스 형태의 긴팔 파자마인데, 모달 원단이라 아주 부드럽거든요. 22,900원이라는 가격도 너무 괜찮아서 여러 디자인 중에... ',
   'bloggername': '아름다운글씨',
   'bloggerlink': 'https://blog.naver.com/tt8u7u',
   'postdate': '20260926'},
  {'title': '미닉스 음식물 처리기 더플렌더 MAX 3L 최저가 저렴하게 사는 방법',
   'link': 'https://blog.naver.com/sst0ne/224423288092',
   'description': '요즘 주방 <b>필수템</b>으로 꼽히는 미닉스 음식물 처리기 더플렌더 MAX 모델을 다른 가정용 음식물 분쇄기... 가구나 <b>신혼부부</b>, 혹은 디자인 예쁜 <b>신혼</b>가전을 찾으시는 분들에게 정말 잘 맞을 수 있어요. 벌레 꼬이는... ',
   'bloggername': '세상 패치노트',
   'bloggerlink': 'https://blog.naver.com/sst0ne',
   'postdate': '20260926'},
  {'title': '<b>신혼부부 필수템</b> 카테고리 오늘쓰임 편한 수기 가계부 사용기',
   'link': 'https://blog.naver.com/shpaw1/224423163684',
   'description': '<b>신혼부부</b>에게 추천해요 요즘 가계부 쓰는 게 필요해서 카테고리 오늘쓰임 편한 수기 가계부를... 각각 지출을 기록하니 서로 어떤 부분에서 비용이 많이 드는지 서로 확인할 수 있어요. 가끔은 서로의 지출을... ',
   'bloggername': '오븐팬의추억',
   'bloggerlink': 'https://blog.naver.com/shpaw1',
   'postdate': '20260926'},
  {'title': '<b>신혼부부 필수템</b> Tefal 매직핸즈 인덕션 프라이팬 세트 후기',
   'link': 'https://blog.naver.com/siyfhfy5/224422862309',
   'description': '제가 처음 써보면서 느낀 장점과 비슷한 부분이 많아서 좋았어요. 다른 분들의 텍스트 후기가 마음에 드네요. 결론 요약 추천 대상 비추천 대상 <b>신혼부부</b> 요리를 잘 하지 않는 분 요리 초보자 비싼 주방용품... ',
   'bloggername': '핸드드립커피이야기',
   'bloggerlink': 'https://blog.naver.com/siyfhfy5',
   'postdate': '20260926'},
  {'title': '<b>신혼</b>살림 추천템 땡스소윤 보관통 내돈내산 후기 | <b>신혼부부</b> 코스트....',
   'link': 'https://blog.naver.com/yoonseul125/224422677483',
   'description': '<b>신혼부부</b> 밀프렙 꿀템 땡스소윤 ✦ . ⁺ . ✦ .. ️ 1년 내돈내산 사용 후기 안녕하세요 윤슬입니다  오늘은 <b>신혼</b>집 <b>필수템</b> 보관통... 냉동이 <b>필수</b>인 바쁜 <b>신혼부부</b> 분들 땡스소윤 세트로 추천드립니다... ',
   'bloggername': 'Love wins all ˚♡ ⋆｡˚',
   'bloggerlink': 'https://blog.naver.com/yoonseul125',
   'postdate': '20260925'},
  {'title': '여름에 완전히 어울리는 반팔 커플 잠옷 세트 후기',
   'link': 'https://blog.naver.com/zpcfobkl4584/224422499916',
   'description': '<b>신혼부부 필수템</b> 최근에 여름 잠옷 세트를 새로 구입했거든요. 하이픈의 여름 반팔 카라 커플 잠옷... 하지만, 저희 <b>부부</b>는 피팅이 잘 돼서 괜찮았어요. 그래도 좀 더 다양한 체형을 고려한 사이즈가 있다면 좋을... ',
   'bloggername': '내마음의여행',
   'bloggerlink': 'https://blog.naver.com/zpcfobkl4584',
   'postdate': '20260925'},
  {'title': '<b>신혼부부 필수템</b> 테팔 인덕션 스텐 티타늄 1X 프라이팬 사용기',
   'link': 'https://blog.naver.com/ditam39/224420692666',
   'description': '프라이팬 고민은 끝 최근에 <b>신혼부부</b>가 주방용품 준비한다고 하길래, 제가 써본 테팔 인덕션 스텐... 왜 샀는지 요즘 <b>부부</b>가 함께 요리하는 모습을 많이 보고, 저도 그럴 거 같아 인덕션 후라이팬을 찾고... ',
   'bloggername': '맛깔난요리',
   'bloggerlink': 'https://blog.naver.com/ditam39',
   'postdate': '20260923'},
  {'title': '[<b>신혼부부 필수템</b>] 레이나 압력솥 추천! 가스압력솥으로 뚝딱 만드....',
   'link': 'https://blog.naver.com/judady-/224420323838',
   'description': '맛있는 집밥 챙겨 드시고 모두 따뜻하고 행복한 하루 보내세요! #레이나압력솥 #레이나압력밥솥 #가스압력솥 #압력밥솥 #인덕션압력밥솥 #PRC2604 #압력솥 #밥솥추천 #냄비밥 #집밥 #<b>신혼부부필수템</b> #집들이선물추천',
   'bloggername': '왈가닥 하우스',
   'bloggerlink': 'https://blog.naver.com/judady-',
   'postdate': '20260922'},
  {'title': '<b>신혼</b>집 서랍에 꼭 있어야 할 것 필링핏 대용량 초박형콘돔  리뷰',
   'link': 'https://blog.naver.com/rorohj2244/224413638587',
   'description': '후기 <b>신혼부부</b>가 콘돔을 고를 때 은근히 고민되는 부분이 많습니다. 너무... <b>신혼부부필수템</b> #<b>신혼부부</b>추천 #콘돔추천 #콘돔리뷰 #가성비콘돔 #얇은콘돔 #커플템 #<b>신혼</b>집<b>필수템</b> #피임용품 #커플용품 #인더파우치',
   'bloggername': 'rorohj2244님의블로그',
   'bloggerlink': 'https://blog.naver.com/rorohj2244',
   'postdate': '20260922'},
  {'title': '서울 동작대교 야외 스냅 후기/한강 웨딩 스냅 장소/<b>필수템</b> 소품,조....',
   'link': 'https://blog.naver.com/aldbqls14/224419200650',
   'description': '예쁜 <b>부부</b>들을 더 예쁘게 담아드리고 싶어서 직접 돌아다니며... 동작대교 선택 이유 문의주신 예비<b>신혼부부</b>께서 야간촬영을... <b>필수템</b>  불꽃놀이 막대기 &gt;&gt; 이게 진짜 분위기 짱짱 만들어줌 조명!!... ',
   'bloggername': '빈둥거리는 일상 소개',
   'bloggerlink': 'https://blog.naver.com/aldbqls14',
   'postdate': '20260921'},
  {'title': '1인 가구 자취생 <b>필수템</b>, 쿠잉 레트로 미니냉장고 REF-D85 2도어 소형 ....',
   'link': 'https://blog.naver.com/bobaejink/224418829730',
   'description': '원룸이나 자취방, 사무실 또는 <b>신혼부부</b>의 서브 공간에서는 가전제품 하나를 고를 때도 디자인과... 쿠잉 레트로 미니냉장고 REF-D85 2도어 소형 원룸 사무실 <b>신혼</b> 슬림 레드 모델은 감각적인 레트로 감성과... ',
   'bloggername': 'IT 전문 블로그, 보배',
   'bloggerlink': 'https://blog.naver.com/bobaejink',
   'postdate': '20260921'},
  {'title': '포천 층간소음매트 <b>신혼부부</b>라면 <b>필수템</b>!',
   'link': 'https://blog.naver.com/wally911/224418544363',
   'description': '5장 + 퍼즐매트 2장 새로운 집에서 시작하는 <b>신혼</b>생활. 깔끔한... 특히 아파트에 거주하는 <b>신혼부부</b>라면 한 번쯤 고민하게 되는 것이... 구조라면 부분적으로 매트를 설치했을 때 생기는 경계와 높이 차이를... ',
   'bloggername': '보들매트',
   'bloggerlink': 'https://blog.naver.com/wally911',
   'postdate': '20260921'},
  {'title': 'LG 식기세척기 DUE6BGH1E 추천! 트루스팀으로 더 깨끗하게 !! 롯데하이....',
   'link': 'https://blog.naver.com/sangjuhimart/224418448381',
   'description': '<b>필수</b> 주방가전으로 자리 잡고 있는데요. 특히 맞벌이 가정, 육아 가정, 집들이를 준비하는 <b>신혼부부</b>들에게는 없어서는 안 될 <b>필수템</b>이... 가정 ✅ <b>신혼</b>집 가전을 준비하는 예비<b>부부</b> ✅ 주방 인테리어까지... ',
   'bloggername': '롯데하이마트 상주점',
   'bloggerlink': 'https://blog.naver.com/sangjuhimart',
   'postdate': '20260921'},
  {'title': '얼라맘마 순진한 맛간장 1인 가구가 고민하는 유통기한 솔루션',
   'link': 'https://blog.naver.com/pmissbraink/224418179387',
   'description': '<b>신혼부부</b>와 자취생 <b>필수템</b> 간장은 많은 가정에서 <b>필수</b>적인 조미료로, 특히 1인 가구에서는 소량으로 유용하게 사용할 수 있는 제품이 필요해요. 얼라맘마 순진한 맛간장은 그러한 필요에 부합하는 제품입니다.... ',
   'bloggername': '마음속태양',
   'bloggerlink': 'https://blog.naver.com/pmissbraink',
   'postdate': '20260921'},
  {'title': '* 공간 활용도 200% 올려주는 자취생&amp;<b>신혼부부 필수템</b>! 벽에 구멍 없....',
   'link': 'https://blog.naver.com/trendhunter-26/224418085680',
   'description': '* 공간 활용도 200% 올려주는 자취생&amp;<b>신혼부부 필수템</b>! 벽에 구멍 없이 레트로 감성 채우는 빈티지 우드 8후크 행거 ✨ 원목 벽걸이 옷걸이 레트로 후크 행거 다용도 걸이 빈티지 우드 8후크 옷걸이 1개 진도z 7,100... ',
   'bloggername': 'Trend Radar',
   'bloggerlink': 'https://blog.naver.com/trendhunter-26',
   'postdate': '20260920'},
  {'title': '<b>신혼부부</b> 냉동밥용기 추천 | 노브랜드 촉촉한끼 냉동밥 보관용기 300....',
   'link': 'https://blog.naver.com/hjst0412/224417150881',
   'description': '<b>신혼부부 필수템</b> 중 하나인 바로 냉동밥용기❄️ 맞벌이 <b>부부</b> 매번 밥을 새로 하기는 귀찮고 그렇다고 즉석밥을 먹는건 찝찝하죠 드디어 정착한 <b>신혼부부</b> 살림템 냉동밥용기 소개해볼게요 노브랜드... ',
   'bloggername': 'Our Diary ෆ',
   'bloggerlink': 'https://blog.naver.com/hjst0412',
   'postdate': '20260919'},
  {'title': '쿠잉 소형냉장고 REF-C120S 슬림 미니냉장고 추천 | 원룸 사무실 <b>신혼</b>....',
   'link': 'https://blog.naver.com/0358aaaa/224411564264',
   'description': '가장 만족했던 부분들: 도어 포켓이 정말 유용했습니다. 자주 마시는... <b>신혼부부</b>가 첫 냉장고로 구매하거나 서브 냉장고가 필요한 경우도 강력 추천입니다. <b>신혼</b>집의 협소한 주방에 대형냉장고를 두기... ',
   'bloggername': '채식주의 호랑이',
   'bloggerlink': 'https://blog.naver.com/0358aaaa',
   'postdate': '20260919'},
  {'title': '커플잠옷 원피스잠옷으로 <b>신혼부부</b>의 달콤한 저녁을 즐겨보세요',
   'link': 'https://blog.naver.com/jdgtqsra/224416858670',
   'description': '<b>신혼부부</b>의 <b>필수템</b> 요즘 부쩍 <b>신혼부부</b>들 사이에서 이 커플잠옷 원피스잠옷이 인기거든요. 그래서 저도... 저와 남편은 지금 <b>신혼</b>인데, 매일 밤 이 잠옷을 입고 다정하게 시간을 보내고 있어요. 고급스러운 소재... ',
   'bloggername': '레트로음악탐구',
   'bloggerlink': 'https://blog.naver.com/jdgtqsra',
   'postdate': '20260919'},
  {'title': '<b>신혼</b>집에 딱! LG전자 트롬 세탁기건조기세트로 뽀송한 하루 시작',
   'link': 'https://blog.naver.com/skdjf76/224416708763',
   'description': '<b>신혼부부</b>들의 <b>필수템</b> 최근 집들이 선물로 LG전자 트롬 세탁기건조기세트를 구매했거든요. 가격은... <b>신혼</b>집에 새로 입주했거나 입주예정인 친구들에게 추천하고 싶어서 후기 남겨볼게요. 구매 계기와 가격 사실... ',
   'bloggername': '라이딩그램',
   'bloggerlink': 'https://blog.naver.com/skdjf76',
   'postdate': '20260919'},
  {'title': '삼성전자 일반 525L 2도어 냉장고 방문설치로 <b>신혼</b>살림 준비하기',
   'link': 'https://blog.naver.com/callua34/224416601578',
   'description': '<b>신혼</b>가정의 <b>필수템</b> <b>신혼부부</b>로서 살림을 시작하면서 냉장고 선택이 제일 고민됐어요. 특히, 공간이... 실제 사용 경험 저희 <b>신혼</b>집의 냉장고는 주말에 장을 보며 <b>필수</b> 아이템이 되었어요. 평일에는 아침 식사로... ',
   'bloggername': '사랑스러운고양이',
   'bloggerlink': 'https://blog.naver.com/callua34',
   'postdate': '20260919'},
  {'title': '<b>신혼부부</b>·1인 가구 <b>필수템</b>! 삼성 삼탠바이미 32인치 M5 스마트 모니....',
   'link': 'https://blog.naver.com/gduddo/224416419115',
   'description': '및 <b>신혼부부</b>  이동식 스마트 스크린을 고민 중이시라면 아래 링크에서 상세한 할인 정보와 스펙을... 피벗모니터 #무선이동식스크린 #세컨드TV #자취방<b>필수템</b> #<b>신혼</b>가전추천 #홈엔터테인먼트 #삼성삼탠바이미',
   'bloggername': '딸은 다이브 님의 블로그',
   'bloggerlink': 'https://blog.naver.com/gduddo',
   'postdate': '20260918'},
  {'title': '식기세척기 Q&amp;A',
   'link': 'https://blog.naver.com/2wngud2/224415951948',
   'description': '요즘 <b>신혼부부</b>님들이나 입주하시는 분들의 <b>필수템</b>! 식기세척기를 구매하시면서 현장에서 가장많이 물어보시는 부분들을 정리해보았습니다. Q:식기세척기 설치 구격 알려주세요 A: 600*815*600 mm 입니다. 위... ',
   'bloggername': 'LG베스트샵 간석오거리 이주형 매니저',
   'bloggerlink': 'https://blog.naver.com/2wngud2',
   'postdate': '20260918'},
  {'title': '주방 <b>필수템</b> 등극! 쿠잉 미니 전자레인지 MC-P20WBF 3개월 써보니',
   'link': 'https://blog.naver.com/jurirsal/224415518728',
   'description': '자취방전자레인지 #<b>신혼부부</b>전자레인지 #1인가구전자레인지 #주방인테리어 #가성비전자레인지 #전자레인지추천 #쿠잉프리즘 #주방<b>필수템</b> #생활가전 #온라인최저가 #초소형전자레인지 #원룸전자레인지... ',
   'bloggername': 'jurirsal님의 블로그',
   'bloggerlink': 'https://blog.naver.com/jurirsal',
   'postdate': '20260918'},
  {'title': '<b>신혼부부</b> 집들이 선물로 완벽♥ 홈카페 감성 가득한 머그컵 세트 추....',
   'link': 'https://blog.naver.com/maliell33/224414347695',
   'description': '오늘은 <b>신혼부부</b> 집들이 선물 <b>필수템</b> 본디자인랩 홈카페 감성 가득한 머그컵 세트, 마이차징머그 세트 리뷰를 포스팅하려고 해요! 요즘 집에서 보내는 시간이 많아지면서 저도 홈카페를 즐기게 되었는데, 예쁜... ',
   'bloggername': 'sweet LARIA',
   'bloggerlink': 'https://blog.naver.com/maliell33',
   'postdate': '20260918'},
  {'title': '휴롬 음식물처리기 3세대 사용 후기, 여름철 음식물쓰레기 고민 해....',
   'link': 'https://blog.naver.com/kjuuu0716/224415170398',
   'description': '들었던 부분 중 하나가 바로 초소형 미니 사이즈였어요. 가로 26cm... 여름철 <b>필수</b> 가전이라고 하는지 하루 만에 바로 깨닫게 되었어요.... <b>신혼부부</b> 주방 가전 <b>필수템</b> 또는 집들이 선물로도 강력 추천드립니다 ෆ... ',
   'bloggername': '크즈의 Wedding KLOG',
   'bloggerlink': 'https://blog.naver.com/kjuuu0716',
   'postdate': '20260917'},
  {'title': '<b>신혼부부</b>의 <b>필수템</b>, 접이식 휴대용 실내화 기내용 여행용 호텔 슬리....',
   'link': 'https://blog.naver.com/dmkzwonhhduxde0ooir/224414741534',
   'description': '<b>신혼</b> 생활을 시작하면서, 집에서 더 편하게 지내고 싶다는 생각이... <b>신혼부부</b>의 <b>필수템</b>, 접이식 휴대용 실내화 기내용 여행용 호텔... 발바닥에 닿는 부분이 부드럽고, 쿠션감이 있어서 오랜 시간 신어도 발이... ',
   'bloggername': '톱니바퀴탐험대장',
   'bloggerlink': 'https://blog.naver.com/dmkzwonhhduxde0ooir',
   'postdate': '20260917'},
  {'title': '<b>신혼부부</b>의 <b>필수템</b>, 크리스탈클라우드 이발기로 깔끔함을 더해요',
   'link': 'https://blog.naver.com/us73r1ydpwu/224414682626',
   'description': '저희 <b>부부</b>도 이발기로 더욱 깔끔한 일상을 즐기고 있답니다. #크리스탈클라우드 #이발기 #바리깡... 가정용 #<b>신혼부부</b> #가성비 #미용 #스타일링 #깔끔한디자인 #관리용이 #<b>신혼</b>템 #집에서이발하기 #편리한사용... ',
   'bloggername': '깔끔한 극장 그림꾼',
   'bloggerlink': 'https://blog.naver.com/us73r1ydpwu',
   'postdate': '20260917'},
  {'title': '[2026 <b>신혼</b>집 인테리어] 호텔 침실 분위기 완성하는 <b>신혼부부 필수템</b> ....',
   'link': 'https://blog.naver.com/zero-oclock/224414541533',
   'description': '4가지 <b>필수</b> 아이템의 선택 기준과 활용법을 정리해 드립니다. 1.사계절 수면의 질을 높이는 구스이불... #<b>신혼부부</b> #<b>신혼</b>집인테리어 #집인테리어 #<b>신혼</b>인테리어 #<b>부부</b>잠옷 #<b>신혼</b>구스이불 #<b>신혼</b>침구... ',
   'bloggername': "zero o'clock",
   'bloggerlink': 'https://blog.naver.com/zero-oclock',
   'postdate': '20260917'},
  {'title': '깔끔한 디자인의 메종드히로안 도마뱀 가죽 카드지갑, <b>신혼부부</b>의 ....',
   'link': 'https://blog.naver.com/latjxopciucarke5roo/224414401143',
   'description': '깔끔한 디자인의 메종드히로안 도마뱀 가죽 카드지갑, <b>신혼부부</b>의 <b>필수템</b>으로 추천해요 결혼을 준비하면서 여러 가지 물건들을 새로 구입했는데, 카드지갑도 그 중 하나였어요. 저희는 평소에 카드나 명함을... ',
   'bloggername': '아침 유자 산책러',
   'bloggerlink': 'https://blog.naver.com/latjxopciucarke5roo',
   'postdate': '20260917'},
  {'title': '주방 <b>필수템</b> 광파오븐렌지 3개월 실사용 후기',
   'link': 'https://blog.naver.com/fqfqhgqhfq/224414330926',
   'description': '오늘은 제가 요즘 완전 빠져있는 주방 <b>필수템</b>을 소개해드리려고... 특히 자취하시는 분들이나 <b>신혼부부</b>에게 완전 강추하는... ✔ 매일 식단 관리하는데 굽는 요리를 자주 하는 분 ✔ 자취방이나 <b>신혼</b>집에 오븐... ',
   'bloggername': 'fqfqhgqhfq님의 블로그',
   'bloggerlink': 'https://blog.naver.com/fqfqhgqhfq',
   'postdate': '20260917'},
  {'title': '둘이 사는데 음식물 처리기까지 필요할까? <b>신혼부부</b>,자취생 <b>필수템</b>!....',
   'link': 'https://blog.naver.com/500dollartrader/224414224550',
   'description': '미생물 음식처리기를 처음 보면 이 부분이 제일 신기한데요. 음식물을 넣어놓으면 안에 있는... [<b>신혼부부</b>,자취생 <b>필수템</b>! 린클이지 보러가기] 린클 이지 음식물처리기 미생물 음식물 쓰레기 분쇄기 음처기... ',
   'bloggername': 'Impulsive Traders Club',
   'bloggerlink': 'https://blog.naver.com/500dollartrader',
   'postdate': '20260916'},
  {'title': '완벽한 <b>신혼</b> 준비 삼성 AI콤보와 직수 AI정수기 세트',
   'link': 'https://blog.naver.com/helprest14/224414013109',
   'description': '<b>신혼 부부</b>를 위한 <b>필수템</b> <b>신혼</b>집 가전을 고민하고 계신가요? 저는 최근에 삼성 AI콤보 세탁 건조기와... 세탁기와 건조기, 정수기는 <b>필수</b>라는 생각이 들어서 삼성 AI콤보 세탁 건조기와 AI정수기 세트를... ',
   'bloggername': '소소한베이킹',
   'bloggerlink': 'https://blog.naver.com/helprest14',
   'postdate': '20260916'},
  {'title': '<b>신혼부부</b>가전·1인가구 <b>필수템</b> 추천! LG 디오스 AI 오브제컬렉션 양문....',
   'link': 'https://blog.naver.com/vhrwnsu17/224413591986',
   'description': '맞벌이 <b>부부</b>라면 주말에 장을 한꺼번에 보거나 반찬과 냉동식품을 넉넉히 준비하는 경우가 많아... #<b>신혼부부</b>가전 #1인가구<b>필수템</b> #<b>신혼</b>가전추천 #혼수가전추천 #LG냉장고 #LG디오스냉장고... ',
   'bloggername': '러블리한여행님의 블로그',
   'bloggerlink': 'https://blog.naver.com/vhrwnsu17',
   'postdate': '20260916'},
  {'title': '<b>신혼부부</b>의 <b>필수템</b>, 때밀이침대 목욕탕 세신 구멍 사우나 용 미용 ....',
   'link': 'https://blog.naver.com/wfejjvtggnfvc5qb/224413556790',
   'description': '<b>신혼부부</b>의 <b>필수템</b>, 때밀이침대 목욕탕 세신 구멍 사우나 용 미용 배드 안마 <b>신혼</b>생활을 시작하면서 저희는 서로의 피로를 풀어줄 방법을 찾고 있었어요. 특히 요즘처럼 날이 쌀쌀해지면 따뜻한 사우나나... ',
   'bloggername': '숲속 관찰자',
   'bloggerlink': 'https://blog.naver.com/wfejjvtggnfvc5qb',
   'postdate': '20260916'},
  {'title': '[주방가전] 쿠쿠 식기세척기 지점 전시 특가 판매',
   'link': 'https://blog.naver.com/glaciers12/224413519829',

In [6]:
df=pd.DataFrame(blog_extractor)

In [7]:
df.head()

,title,link,description,bloggername,bloggerlink,postdate
0,무선 이어폰 소니 WF-1000XM5 블랙 최저가 비교부터 노이즈캔슬링 성능....,https://blog.naver.com/bboksunga/224426002746,출퇴근길 대중교통 소음이나 카페의 시끄러운 백색소음 속에서 온전히 음악에 집중하고 ...,복숭아 재테크,https://blog.naver.com/bboksunga,20260929
1,"대학생·<b>직장인</b> 태블릿 추천: 필기, 영상 시청, 작업용도에 맞는 아....",https://blog.naver.com/forevertrb/224425734031,"스마트폰보다 시원한 대화면, 노트북보다 가벼운 휴대성으로 대학생과 <b>직장인</b...",기묘한 지식 상점,https://blog.naver.com/forevertrb,20260929
2,PPSU 꿈찾는 곰 젖병 아기의 수유습관을 지키기 위한 구성품 정보,https://blog.naver.com/gutsusetsu198427/224425...,아기 수유를 위한 <b>필수품</b> 육아를 돌보는 <b>직장인</b>들은 퇴근 후...,자기다짐,https://blog.naver.com/gutsusetsu198427,20260929
3,[제목] 가성비 태블릿 추천! 2026년 대학생 인강·필기용 용도별 사양 ....,https://blog.naver.com/jyp940106/224425093989,지난 포스팅에서는 하반기 재테크 <b>필수품</b>인 시중은행 파킹통장 최고 금리 ...,jyp940106님의블로그,https://blog.naver.com/jyp940106,20260928
4,[제목] 2026년 가성비 노트북 추천! <b>직장인</b> 대학생을 위한 용도별 ...,https://blog.naver.com/jyp940106/224425091851,스마트폰만큼이나 우리 일상에서 빼놓을 수 없는 <b>필수품</b>이 바로 '노트북'...,jyp940106님의블로그,https://blog.naver.com/jyp940106,20260928

In [8]:
import re

def txtcleaner(txt):
    if not isinstance(txt, str):
        return ""
    
    txt=re.sub(r'[^가-힣\s]',' ', txt) # 가-힣과 공백을 제외한 모든 문제 제거하는 메서드
    txt=re.sub(r'\s+',' ', txt).strip() # 연소 공백, 줄바꿈 등을 공백 하나로 정리
    return txt
target_col=['title','description']
for col in target_col:
    df[col]=df[col].apply(txtcleaner)

In [9]:
drop_cols=['bloggername','description','bloggerlink'] # 블로그 이름은 의미가 없고, description 대신 본문을 크롤링 할 것이기 때문에, 지움. bloggerlink도 의미 없음
df=df.drop(columns=drop_cols)

In [10]:
df

,title,link,postdate
0,무선 이어폰 소니 블랙 최저가 비교부터 노이즈캔슬링 성능,https://blog.naver.com/bboksunga/224426002746,20260929
1,대학생 직장인 태블릿 추천 필기 영상 시청 작업용도에 맞는 아,https://blog.naver.com/forevertrb/224425734031,20260929
2,꿈찾는 곰 젖병 아기의 수유습관을 지키기 위한 구성품 정보,https://blog.naver.com/gutsusetsu198427/224425...,20260929
3,제목 가성비 태블릿 추천 년 대학생 인강 필기용 용도별 사양,https://blog.naver.com/jyp940106/224425093989,20260928
4,제목 년 가성비 노트북 추천 직장인 대학생을 위한 용도별 고,https://blog.naver.com/jyp940106/224425091851,20260928
...,...,...,...
995,여행 필수품 바우아토 가벼운 보조배터리 왜 써야 할까,https://blog.naver.com/jk0918/224335694882,20260705
996,구글 제미나이 유료 프로 가격 싸게 이용하는 방법,https://blog.naver.com/lth0713/224336537762,20260704
997,매번 품절 대란 밥클럽 아침밥 할인으로 쟁여두기 인증,https://blog.naver.com/klsaska/224336525851,20260704
998,직장인 하루루틴의 필수품 루업 굿데이 세트,https://blog.naver.com/juvenile20/224336335900,20260704
999,그램 코어 세대 램 단품 단품,https://blog.naver.com/enscq14298/224335442251,20260704

In [12]:
# 블로그 HTML 구조를 파악한 뒤에 차례로 크롤링 해야 함
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time
body_data=[]

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36"
    )
}
def body_text_extractor(url):
    print('블로그 본문을 수집합니다.')
    try:
        # 1. 외부 네이버 블로그 페이지 요청
        response = requests.get(
            url,
            headers=HEADERS,
            timeout=10
        )
        
        response.raise_for_status()

        outer_soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # 2. 실제 본문을 담은 iframe 주소 찾기
        iframe = outer_soup.select_one("iframe#mainFrame")

        if iframe is not None and iframe.get("src"):
            inner_url = urljoin(url, iframe["src"])

            # 3. iframe 내부 페이지 재요청
            inner_response = requests.get(
                inner_url,
                headers=HEADERS,
                timeout=10
            )
            inner_response.raise_for_status()

            soup = BeautifulSoup(
                inner_response.text,
                "html.parser"
            )

        else:
            # iframe 없는 주소(PostView 등)는 현재 HTML 그대로 사용
            soup = outer_soup

        # 4. 최신 스마트에디터 본문 선택
        body_tag = soup.select_one("div.se-main-container")

        # 5. 구형 에디터 구조도 대비
        if body_tag is None:
            body_tag = soup.select_one("#postViewArea")

        if body_tag is None:
            print(f"본문 영역을 찾지 못함: {url}")
            return None

        print('네이버 블로그 본문 크롤링을 완료했습니다. ')
        
        time.sleep(3)
        return body_tag.get_text(
            separator="\n",
            strip=True)
    
    except requests.RequestException as e:
        print(f"요청 오류: {url} / {e}")
        return None

html에서 iframe 구조는 HTML 페이지 안에서 다른 웹 문서나 외부 서비스를 작은 독립 창처럼 삽입하기 위해서 쓰는 것으로, 다른페이지를 직접 구현하지 않고 가져와서 보여주기 위함
네이버 블로그의 맥락에서는 서비스에서 공통으로 활용하는 툴과, 실제 게시글 콘텐츠를 분리하기 위함

In [13]:
df_sample=df.iloc[:3,:].copy()

In [14]:
df_sample['content']=df_sample['link'].apply(lambda x: body_text_extractor(x))

블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.
블로그 본문을 수집합니다.
네이버 블로그 본문 크롤링을 완료했습니다.

In [15]:
df_sample['content_cleaned']=df_sample['content'].apply(lambda x: txtcleaner(x))

In [16]:
df_sample

,title,link,postdate,content,content_cleaned
0,무선 이어폰 소니 블랙 최저가 비교부터 노이즈캔슬링 성능,https://blog.naver.com/bboksunga/224426002746,20260929,​\n​\n출퇴근길 대중교통 소음이나 카페의 시끄러운 백색소음 속에서 온전히 음악에...,출퇴근길 대중교통 소음이나 카페의 시끄러운 백색소음 속에서 온전히 음악에 집중하고 ...
1,대학생 직장인 태블릿 추천 필기 영상 시청 작업용도에 맞는 아,https://blog.naver.com/forevertrb/224425734031,20260929,"스마트폰보다 시원한 대화면, 노트북보다 가벼운 휴대성으로 대학생과 직장인 모두에게 ...",스마트폰보다 시원한 대화면 노트북보다 가벼운 휴대성으로 대학생과 직장인 모두에게 필...
2,꿈찾는 곰 젖병 아기의 수유습관을 지키기 위한 구성품 정보,https://blog.naver.com/gutsusetsu198427/224425...,20260929,"이 글에는 쇼핑 커넥트 상품이 포함되어 있으며,\n판매 발생시 크리에이터는 수수료를...",이 글에는 쇼핑 커넥트 상품이 포함되어 있으며 판매 발생시 크리에이터는 수수료를 받...

In [ ]:
df['content']=df['link'].apply(lambda x: body_text_extractor(x))